### ISSUE TITLE
Adding video call feature for mentoring session

### ISSUE THREAD

**Issue by tyohan** [bearmentor/bearmentor.com#14]
Hi,

I like to contribute to this platform by adding a video call feature that can be used for mentoring sessions. The feature will be similar to Google Meet or Zoom, but it will be integrated directly into the Bearmentor web app. With this, we can control and track the users who can join the mentoring session. We have a basic demo [here](https://room.inlive.app) developed with NextJS. The source code is available on [our Github repo](https://github.com/inlivedev/inlive-room).

The feature will use [inLive Hub API](https://inlive.app/realtime-interactive) for the WebRTC SFU backend. There will be no cost will occur for now because the inLive Hub itself is still in beta, but it will have cost in the future. We can discuss how we can cover this cost later. 

What do you think @mhaidarhanif, I can just start a branch and start coding the feature there if you're open to it.

**Comment by mhaidarhanif** [comment]
Hi @tyohan

Thanks for the heads up

Sure thing, there are some things we have to ensure:

A. Yes you can start a branch and coding it there. 2 options: do you want to get invited as a team member here so you can start the branch from the primary repo or you want to use your fork repo? You can also check if this repo can run fine on your side just fine, hopefully everything's clear on the README.

B. As you can see this repo is using Remix, so we also have to conform with the Remix structure/idiom. How it'll integrate with the whole codebase? Because I'll also assume the data integration need to affect new models through Prisma ORM as well.

C. Any other ideas are welcome on how to integrate inLive into the platform. As I haven't got my hand into inLive yet, so have to spend a bit of time to explore it first.

Can also check issue #9 which elaborate on the main mentorship UX. The video call flow would be added into there later.

**Comment by mhaidarhanif** [comment]
You're welcome @tyohan 

A. Alright I'ved added you as the repo contributor.

B. Got it. Probably need some more definitive guide to help on the React side. For the database side, then there will be a new model for handling the `Meeting` that contains a `@unique` `roomId` for various purpose, or specific fields like `inliveRoomId`, `zoomRoomId`, `meetRoomId`, `aroundRoomId`.

C. Got it. Notice I highlight some things regarding the manual process, while we're figuring out the automated system.

Sure thing, as in #9 there's a priority on the main flow, we're waiting for the guide on using JS SDK with React. Because I won't be the sole primary maintainer, therefore the documentation will be very relied upon.

**Comment by mhaidarhanif** [comment]
cc @bearmentor/collaborator, especially @krowter as he works on part of Vidio.com then maybe had some insights on this.

**Comment by krowter** [comment]
Hi @tyohan sorry for the late reply

I'm curious about the streaming part. Since the users may not have the best internet connection, will the stream quality selection be done on the SFU part based on the user's bandwidth, or the client/web app have to manually select the quality?

**Comment by tyohan** [comment]
@krowter currently inLive streaming is not supporting simulcast which allow the sfu to do the adaptive streaming. But this is already WIP so it will be supportrd in the next few weeks. Later the client will automatically receive the most optimal bitrates when simulcast is enabled. The client can also manualy adjust the streaming bitrate if needed.

**Comment by krowter** [comment]
@tyohan I see. Noted 👍
